### PR TITLE
Adding more data collection for TFE

### PR DESCRIPTION
**Pull request by anniehedgpeth**
Related to #186, this branch adds some more TFE data collection based on [TF-450](https://hashicorp.atlassian.net/browse/TF-450).

[TF-549](https://hashicorp.atlassian.net/browse/TF-549) - gathers the number of users
[TF-550](https://hashicorp.atlassian.net/browse/TF-550) - gathers the number of runs
[TF-461](https://hashicorp.atlassian.net/browse/TF-461) - gathers whether or not it's airgapped
[TF-459](https://hashicorp.atlassian.net/browse/TF-459) - gathers the following:
- Object Storage - Type
- Operational Mode
- Worker Memory capacity limit
- Worker CPU capacity limit
- Concurrent Run limit
- Custom Worker Image?
- Log Forwarding

I tested this on a dev instance of TFE, and I got the desired output with the correct redactions. Happy to share if anyone would like to see them before approving.

### CODE REVIEW

**Review by mkcp — APPROVED** [review]
@anniehedgpeth apologies for the delay reviewing this, the team has been at an org-level offsite. LGTM 👍

**Comment by anniehedgpeth** [comment]
> @anniehedgpeth apologies for the delay reviewing this, the team has been at an org-level offsite. LGTM 👍

No worries at all! Alicia gave me a heads up that you were all on your offsite. :) Thanks for the review!

**Comment by anniehedgpeth** [comment]
As I don't have permission to merge, I will leave it up to your team's discretion for when to merge.

**Comment by mkcp** [comment]
> As I don't have permission to merge, I will leave it up to your team's discretion for when to merge.

There's no further feedback from other tagged reviewers so I'm merging away.

**Pull request merged**
